In [6]:
import pandas as pd
import numpy as np



### 1. **What movie had the most expensive budget, how much is it? **
<details>
  <summary>Hint</summary>
  Use the `max` function to find the highest value in the 'Budget' column.  
  Example: `df['Budget'].max()`
</details>

---

### 2. **Which movie made the most at the box office?**
<details>
  <summary>Hint</summary>
  Similar to the previous question, use the `max` function on the 'Box Office' column.  
  Example: `df['Box Office'].max()`
</details>

---

### 3. **What is the average budget of all movies?**
<details>
  <summary>Hint</summary>
  Use the `mean` function to calculate the average value of the 'Budget' column.  
  Example: `df['Budget'].mean()`
</details>

---

### 4. **Which director has the biggest average box office?**
<details>
  <summary>Hint</summary>
  Use the `groupby()` function on the 'Director' column and compute the mean for the box office column.  
  Example: `df.groupby('Director')['Box Office'].mean()`
</details>

---

### 5. **What is the total box office revenue for all movies?**
<details>
  <summary>Hint</summary>
  Use the `sum` function on the 'Box Office' column to get the total.  
  Example: `df['Box Office'].sum()`
</details>

---

### 6. **What is the biggest budget for a comedy movie?**
<details>
  <summary>Hint</summary>
  Filter the DataFrame for movies where the genre is 'Comedy' before using `max` on the 'Budget' column.  
  Example: `df[df['Genre'] == 'Comedy']['Budget'].max()`
</details>



---

### 8. **Which movie has the highest box office revenue in the action genre?**
<details>
  <summary>Hint</summary>
  Filter the DataFrame for 'Action' in the 'Genre' column, then use `max` on the 'Box Office' column.  
  Example: `df[df['Genre'] == 'Action']['Box Office'].max()`
</details>

---

### 9. **Which director's movies have generated the most box office revenue in total?**
<details>
  <summary>Hint</summary>
  Group the DataFrame by 'Director', then use the `sum` function on the 'Box Office' column for each group.  
  Example: `df.groupby('Director')['Box Office'].sum().idxmax()`
</details>


---

### 11. **Which genre has the highest average budget?**
<details>
  <summary>Hint</summary>
  Group by 'Genre', then use the `mean` function on the 'Budget' column to calculate the average for each genre.  
  Example: `df.groupby('Genre')['Budget'].mean().idxmax()`
</details>

---

### 12. **Which movie had the largest box office revenue relative to its budget (box office-to-budget ratio)?**
<details>
  <summary>Hint</summary>
  Create a new column for the ratio, then use the `max` function to find the highest value.  
  Example: `df['Ratio'] = df['Box Office'] / df['Budget']; df['Ratio'].idxmax()`
</details>

---

### 13. **Compute the benefit (Box Office - Budget) for each movie and create a new column.**

<details>
  <summary>Hint</summary>
  You can create a new column called 'Benefit' by subtracting the 'Budget' column from the 'Box Office' column.  
  Example: `df['Benefit'] = df['Box Office'] - df['Budget']`
</details>

---

### 14. **Compute the average benefit by year to see if it increases over time.**

<details>
  <summary>Hint</summary>
  Use the `groupby()` function on the 'Release Year' column and compute the average of the 'Benefit' column.  
  Example: `df.groupby('Release Year')['Benefit'].mean()`
</details>

---

This structure allows for easier navigation through the questions and includes helpful hints for each one. The last two questions handle calculating the benefit for each movie and analyzing trends over time.

In [34]:
# We load the clean dataframe 
df = pd.read_csv("data/american_movies_with_budget_2010.csv", index_col=0)
df.head()

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot,Budget,Box Office,Clean_Budget,Clean_Box_Office
15776,2010,127 Hours,American,Danny Boyle,"James Franco, Amber Tamblyn, Kate Mara, Clémen...","biography, drama",https://en.wikipedia.org/wiki/127_Hours,Mountaineer Aron Ralston goes hiking at Utah's...,$18 million[3],$60.7 million[3],18.0,60.7
15777,2010,The A-Team,American,Joe Carnahan,"Liam Neeson, Bradley Cooper, Quinton ""Rampage""...","action, adventure",https://en.wikipedia.org/wiki/The_A-Team_(film),"John ""Hannibal"" Smith is held captive in Mexic...",$100–110 million[2][3],$177.2 million[3],105.0,177.2
15780,2010,Alice in Wonderland,American,Tim Burton,"Johnny Depp, Anne Hathaway, Helena Bonham Cart...","family, fantasy",https://en.wikipedia.org/wiki/Alice_in_Wonderl...,Troubled by a strange recurring dream and mour...,$150[2][3]–$200[4] million,$1.025 billion[5],175.0,1025.0
15781,2010,All Good Things,American,Andrew Jarecki,"Ryan Gosling, Kirsten Dunst, Frank Langella, K...",mystery,https://en.wikipedia.org/wiki/All_Good_Things_...,"In 1970s New York City, David Marks (Gosling),...",$60 million,$1.8 million[2],60.0,1.8
15782,2010,Alpha and Omega,American,"Anthony Bell, Ben Gluck","Justin Long, Hayden Panettiere, Dennis Hopper,...","animated, comedy, drama, family",https://en.wikipedia.org/wiki/Alpha_and_Omega_...,"In Alberta, Canada's Jasper National Park, Kat...",$20 million[3],$50.5 million[4],20.0,50.5

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Wiki Page,Plot,Budget,Box Office,Clean_Budget,Clean_Box_Office
15776,2010,127 Hours,American,Danny Boyle,"James Franco, Amber Tamblyn, Kate Mara, Clémen...","biography, drama",https://en.wikipedia.org/wiki/127_Hours,Mountaineer Aron Ralston goes hiking at Utah's...,$18 million[3],$60.7 million[3],18.0,60.7
15777,2010,The A-Team,American,Joe Carnahan,"Liam Neeson, Bradley Cooper, Quinton ""Rampage""...","action, adventure",https://en.wikipedia.org/wiki/The_A-Team_(film),"John ""Hannibal"" Smith is held captive in Mexic...",$100–110 million[2][3],$177.2 million[3],105.0,177.2
15780,2010,Alice in Wonderland,American,Tim Burton,"Johnny Depp, Anne Hathaway, Helena Bonham Cart...","family, fantasy",https://en.wikipedia.org/wiki/Alice_in_Wonderl...,Troubled by a strange recurring dream and mour...,$150[2][3]–$200[4] million,$1.025 billion[5],175.0,1025.0
15781,2010,All Good Things,American,Andrew Jarecki,"Ryan Gosling, Kirsten Dunst, Frank Langella, K...",mystery,https://en.wikipedia.org/wiki/All_Good_Things_...,"In 1970s New York City, David Marks (Gosling),...",$60 million,$1.8 million[2],60.0,1.8
15782,2010,Alpha and Omega,American,"Anthony Bell, Ben Gluck","Justin Long, Hayden Panettiere, Dennis Hopper,...","animated, comedy, drama, family",https://en.wikipedia.org/wiki/Alpha_and_Omega_...,"In Alberta, Canada's Jasper National Park, Kat...",$20 million[3],$50.5 million[4],20.0,50.5